<style>

    td{
        width:200px;
    }
    table{
        500px;
    }
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        align-self: center ;
        overflow:hidden
    }
</style>


<h1>Toptal Faq</h1>
	<table class="data table" id="test-data-table" >
		<thead>
			<tr>
			    <th scope="col" class="col id">ID</th>
			    <th scope="col" class="col title">Title</th>
			    <th scope="col" class="col image">Image</th>
			    <th scope="col" class="col author">Description</th>
			</tr>
		</thead>

		<tbody>
			<?php foreach($block->getFaqs() as $data): ?>

			<tr>
				<td data-th="ID" class="col title"><?php echo $data->getId(); ?></td>
				<td data-th="Title" class="col author"><?php echo $data->getTitle(); ?></td>
				<td data-th="Image" class="col author"><img src="<?php echo $data->getImage(); ?>"></td>
				<td width="100" data-th="Description" class="col content"><?php echo substr($data->getDescription(), 0, 255); ?></td>
			</tr>
			  
			<?php endforeach; ?>

		</tbody>
	</table>
			<?php if ($block->getPagerHtml()): ?>
			    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
			<?php endif ?>

